<?php

namespace Database\Seeders\Fixed;

use App\Eco\Measure\MeasureCategory;
use Illuminate\Database\Seeder;

class MeasureCategoriesSeeder extends Seeder
{
    public function run(): void
    {
        MeasureCategory::upsert([
            ['name' => 'Vloerisolatie', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Gevelisolatie', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Dakisolatie', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Isolatieglas', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Kierdichting', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Ventilatie', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Cv-ketel', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Warmtepomp', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Biomassa', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Warmte afgifte', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Zonnepanelen', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Zonneboiler', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Opslag', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Overig', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Domotica', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Leidingisolatie overig', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Warm water toestel', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Energiebespaaradvies', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Energiebespaarcoaching', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Energieconciërge', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Woningopname', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Lampen', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Kleine maatregel', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Onderhoud', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Mobiliteit', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Woningaanpassingen', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Witgoed', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
            ['name' => 'Energie aansluiting', 'uses_wf_create_opportunity' => 0, 'measure_id_wf_create_opportunity' => null, 'opportunity_status_id_wf_create_opportunity' => null, 'uses_wf_create_quotation_request' => 0, 'organisation_id_wf_create_quotation_request' => null, 'uses_wf_email_quotation_request' => 0, 'email_template_id_wf_create_quotation_request' => null, 'calendar_background_color' => '#265985', 'calendar_text_color' => '#ffffff'],
        ], ['name'], [
            'uses_wf_create_opportunity',
            'measure_id_wf_create_opportunity',
            'opportunity_status_id_wf_create_opportunity',
            'uses_wf_create_quotation_request',
            'organisation_id_wf_create_quotation_request',
            'uses_wf_email_quotation_request',
            'email_template_id_wf_create_quotation_request',
            'calendar_background_color',
            'calendar_text_color',
        ]);
    }
}