<?php

namespace Database\Seeders\Fixed;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

class PermissionsSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'create_person',
            'view_person',
            'update_person',
            'delete_person',
            'create_organisation',
            'view_organisation',
            'update_organisation',
            'delete_organisation',
            'update_contact_iban',
            'update_contact_owner',
            'manage_group',
            'manage_user',
            'manage_opportunity',
            'manage_task',
            'manage_intake',
            'manage_marketing',
            'manage_measure',
            'create_document',
            'view_document',
            'create_document_template',
            'view_document_template',
            'view_audit_trail',
            'view_mailbox',
            'create_mailbox',
            'manage_housing_file',
            'view_team',
            'create_team',
            'manage_quotation_request',
            'manage_participation',
            'manage_project',
            'manage_financial',
            'import',
            'manage_webform',
            'manage_mailgun_domain',
            'manage_portal_settings',
            'manage_cooperation_settings',
            'create_hoom_dossier',
            'create_laposta_list',
            'menu_contacts',
            'menu_projects',
            'menu_energy_saving',
            'menu_contact_groups',
            'menu_email',
            'menu_marketing',
            'menu_tasks',
            'menu_agenda',
            'menu_processes',
            'menu_documents',
            'menu_financial',
            'menu_workflow',
            'menu_general_settings',
            'menu_portal_settings',
            'menu_organisations',
            'menu_persons',
            'menu_housing_files',
            'menu_intakes',
            'menu_opportunities',
            'menu_quotation_requests',
            'menu_measures',
            'view_email',
            'view_task',
            'view_note',
            'view_participation',
            'view_intake',
            'view_opportunity',
            'view_housing_file',
            'view_contact_group',
            'view_order',
            'view_invoice',
            'view_financial_overview',
            'view_contact_general',
            'view_contact_address',
            'view_contact_email',
            'view_contact_phone',
            'view_contact_quotation',
            'view_contact_coach_quotation',
            'view_contact_campaign',
            'view_contact_occupation',
            'view_contact_other',
            'view_contact_portal_user',
            'view_contact_note',
            'view_contact_conclusion',
            'view_project',
            'view_jobs_log',
            'view_twinfield_log',
            'view_financial',
            'view_cooperation_settings',
            'view_webform',
            'view_email_template',
            'view_user',
            'view_email_team',
            'create_email_template',
            'create_contact_address',
            'create_contact_email',
            'create_contact_phone',
            'create_contact_occupation',
            'create_contact_note',
            'update_contact_general',
            'update_contact_address',
            'update_contact_email',
            'update_contact_phone',
            'update_contact_occupation',
            'update_contact_other',
            'update_contact_portal_user',
            'update_contact_note',
            'delete_contact_address',
            'delete_contact_email',
            'delete_contact_phone',
            'delete_contact_occupation',
            'delete_contact_portal_user',
            'delete_contact_note',
            'update_contact_conclusion',
            'download_contact',
            'download_contact_consumption',
            'update_contact_group_members',
            'manage_coach_planning',
            'view_housing_file_log',
            'manage_free_fields',
            'menu_dongles',
            'manage_dongles',
            'menu_participations',
            'menu_financial_overviews',
            'manage_financial_overview',
            'view_marketing',
            'view_measure',
            'view_quotation_request',
            'menu_intake_sources',
            'manage_intake_sources',
            'view_free_fields_field_log'
        ];

        foreach (array_unique($permissions) as $permission) {
            Permission::findOrCreate($permission, 'api');
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}